config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'cart/index'

  get 'site/about'

  get 'site/contact'
  
  get '/about' => 'site#about'
  
  get '/contact' => 'site#contact'
  
  get '/Admin' => 'user#admin_login'
  
  get '/logout' => 'user#logout'
  
  get '/cart' => 'cart#index'
  
  get '/cart/clear' => 'cart#clearCart'
  
  get '/cart/:id' => 'cart#add'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

  resources :items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord::Base
 belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def add
    # get the id of the product
    id = params[:id]
    #create new cart if none exists
    if session[:cart] then
        cart = session[:cart]
    else
        session[:cart] = {}
        cart = session[:cart]
    end
    
    #increment the value if product in cart else set to 1
    
    if cart[id] then
        cart[id] = cart[id] + 1
    else
        cart[id] = 1
    end
    # redirect to cart display page
    redirect_to :action => :index
    
  end
  
  def clearCart
    # set session variables to nil and redirect
    session[:cart] = nil
    redirect_to :action => :index
  end
    
  def index
      #if there is a cart pass it to page for display
      # else pass an empty value
      if session[:cart] then      
        @cart = session[:cart]
      else
        @cart = {}
      end  
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

   def new
@profile = Profile.new
@profile.user_id = current_user.id
respond_to do |format|
format.html # new.html.erb
format.json { render json: @profile }
    end
end
  
  
  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :email, :user_id)
    end
    
    def signedinuserprofile profile = Profile.find_by_user_id(current_user.id) 
    if profile.nil? redirect_to "/profiles/new" 
    else @profile = Profile.find_by_user_id(current_user.id) redirect_to "/profiles/#{@profile.id}"
        end 
    end
    
   
    
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def login
    
    end
    
    def admin_login
        session[:login] = 1
        session[:cart] = nil
        flash[:notice] ="Admin login Successful"
        redirect_to :controller => :items    
    end
    
    def logout
        session[:login] = nil
        session[:cart] = nil
        flash[:notice] = "You have successfully logged out"
        redirect_to :controller => :items
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>
<% if @cart.empty? %>
    <p>Your Cart is Empty</p>
<% end %>

<% total = 0 %>

<table class="cart">

    <tr>
        <td class="legent"></td>
        <td class="legent">Item</td>
        <td class="legent">Price</td>
        <td class="legent">Qty</td>
        <td class="legent">Total</td>
    </tr>
    
    <% @cart.each do |id, quantity | %>    
        <% item = Item.find_by_id(id) %>
        <tr>
            <td>
                <div class="image">
                    <%= link_to (image_tag item.image_url, :style => "height:40px"), item %>
                </div>
            </td>
            <td class="title"><%= link_to item.title, item %></td>
            <td class="price"><%= number_to_currency(item.price) %></td>
            <td class="quantity"><%=  quantity %></td>
            <td class="price"><%= number_to_currency(quantity * item.price, :unit => "f") %></td>
        
        </tr>
        <% total += quantity * item.price %>    
    <% end %>
    
    <tr>
        <td colspan="4">
            <div class="total">Total</div>
        </td>
        <td>
            <div class="price">
                <%= number_to_currency(total, :unit => "Eur") %>
            </div>
        </td>
    </tr>


</table>
<p>
    <%= link_to 'Continue Shopping', :controller => :items %>
</p>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><% notice %></p>

<h1>Catalog</h1>
<table class="catalog">
    <% @items.each do |item| %>
    <tr>
        <td>
            <div class="image">
                <%= link_to (image_tag item.image_url, :style =>"height:100px") ,item %>    
            </div>    
        </td>
        <td>
            <div class="title">
                <%= link_to item.title ,item %>    
            </div>       
            <div class="description">
                <%= link_to item.description ,item %>    
            </div>       
            <div class="price">
                <%= link_to item.price ,item %>    
            </div>
            <div class="links">
                <% if session[:login] == 1 %>
                    <%= link_to 'Edit', edit_item_path(item) %>
                    <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>                
                                   
                <% else %>                
                    <a href="/cart/<%= item.id %>">Add To Cart</a><br><br>
                <% end %>
            </div>
        </td>
        
    
    </tr>
    <% end %>

</table>
<% if session[:login] == 1 %>
    <p><%= link_to 'New Item', new_item_path %></p>
<% end %>



<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Golfstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id='header'>

</div>
<div id='menu'>
    <div id='navbar'>
        <ul>        
            <li><a href='/items'>Products</a></li>
            <li><a href='/about'>About</a></li>
            <li><a href='/contact'>Contact</a></li>
            <li><a href='/Admin'>Login</a></li>
            <li><a href='/logout'>Logout</a></li>
        </ul>
    
    </div>
    <div id='container'>
        <div id='content'>
        
            <p class="notice"> <%= flash[:notice] %></p>
            <%= yield %>
        </div>
        <div id='first-column'>
            <div class='loginbox'>
                <h2 class='BoxHeaders'>Login Here ...</h2>
            </div>
            <div class='searchbox'>
                <h2 class="BoxHeaders"> Search Catalog</h2>
            </div>        
        </div>    
    </div>
    <div id='footer'>
    <h6 class="fottertext"> %copy; Online Golf Store &trade; 2016 </h6>
    
    </div>

</div>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.email %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/contact.html.erb
<h1>Site#contact</h1>
<p>Find me in app/views/site/contact.html.erb</p>